import type { Metadata } from "next";
import "./globals.css";
import ConditionalLayout from "@/components/ConditionalLayout";
import { Lexend } from "next/font/google";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Sta. Rita, Samar | Real Property Tax Monitoring System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} antialiased hsansen overflow-hidden font-(--font-lexend)`}>
        <ConditionalLayout>{children}</ConditionalLayout>
      </body>
    </html>
  );
  
}